{% set name = "logmuse" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 298c3336cbca049de2f3d6d4bc1ea4ca5d9d6154c748f34cfc86e89d31e3fc9f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - logmuse

about:
  home: https://github.com/databio/logmuse/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Logging setup tool

extra:
  recipe-maintainers:
    - stolarczyk
    - khoroshevskyi
