{% set name = "logmuse" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a639d795f33d6876766033dea3c4ceb51617029e5f6e0aa390e7c4bc3012624d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - python >=3.8

test:
  imports:
    - logmuse

about:
  home: https://github.com/databio/logmuse/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Logging setup tool

extra:
  recipe-maintainers:
    - stolarczyk
    - khoroshevskyi
