schema_version: 1

context:
  name: logmuse
  version: "0.3.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: e7035e216bbae03098506e863ab733c42ca3e6a9713444a1d159971da54ae04f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - logmuse
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Logging setup tool
  license: BSD-2-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/databio/logmuse

extra:
  recipe-maintainers:
    - stolarczyk
    - khoroshevskyi
